import os
import json
from dotenv import load_dotenv
from openai import OpenAI
import spotipy
from spotipy.oauth2 import SpotifyOAuth

# Load API credentials from your private environment file
load_dotenv()

# Initialize API clients
openai_client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

sp = spotipy.Spotify(auth_manager=SpotifyOAuth(
    client_id=os.getenv("SPOTIPY_CLIENT_ID"),
    client_secret=os.getenv("SPOTIPY_CLIENT_SECRET"),
    redirect_uri=os.getenv("SPOTIPY_REDIRECT_URI"),
    scope="playlist-modify-public"
))

def get_ai_tracks(vibe_prompt):
    print("\n🤖 AI is brainstorming tracks matching your vibe...")
    
    system_instruction = (
        "You are an expert music curator. The user will give you a specific aesthetic mood. "
        "Return exactly 10 REAL, existing songs and artists that match this vibe perfectly. "
        "You MUST respond ONLY with a raw JSON object matching this structure: "
        '{"playlist_name": "Suggested Catchy Name", "tracks": [{"title": "Song Title", "artist": "Artist Name"}]}'
    )

    response = openai_client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[
            {"role": "system", "content": system_instruction},
            {"role": "user", "content": vibe_prompt}
        ],
        response_format={"type": "json_object"}
    )
    
    return json.loads(response.choices.message.content)

def build_spotify_playlist(playlist_data):
    user_id = sp.current_user()["id"]
    playlist_name = playlist_data["playlist_name"]
    tracks = playlist_data["tracks"]
    
    print(f"🎵 Creating Spotify playlist: '{playlist_name}'...")
    new_playlist = sp.user_playlist_create(user=user_id, name=playlist_name, public=True, description="Generated by VibeAI")
    
    track_uris = []
    for track in tracks:
        query = f"track:{track['title']} artist:{track['artist']}"
        search_result = sp.search(q=query, type="track", limit=1)
        
        try:
            track_uri = search_result["tracks"]["items"]["uri"]
            track_uris.append(track_uri)
            print(f"✅ Found: {track['title']} - {track['artist']}")
        except (IndexError, KeyError):
            print(f"❌ Could not find on Spotify: {track['title']} by {track['artist']}")
            
    if track_uris:
        sp.playlist_add_items(playlist_id=new_playlist["id"], items=track_uris)
        print(f"\n🎉 Success! Your playlist is ready. Check your Spotify app!")
    else:
        print("\n😢 Oops, couldn't find any of the tracks on Spotify.")

if __name__ == "__main__":
    print("✨ Welcome to the AI Spotify Vibe Playlist Generator ✨")
    user_vibe = input("Describe your vibe (e.g., 'An 80s workout video hosted by a wizard'): ")
    
    try:
        ai_recommendations = get_ai_tracks(user_vibe)
        build_spotify_playlist(ai_recommendations)
    except Exception as e:
        print(f"\nAn error occurred: {e}")
